#!/usr/bin/env python3
"""Low-budget alternative to v2-real: weight and energy, from the same models as the main plan.

    python lowbudget.py        # -> v2-real/lowbudget/weight.md and energy.md

Only the parts that change are listed here; everything else is v2-real's (payload.py, energy.py).
The product choices and prices are in v2-real/lowbudget/budget.md.
"""
import os

import energy as E
import payload as P

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "v2-real", "lowbudget")

# Weight: (prefix of the v2-real line, new name, new kg or None to drop it). Same x as before.
SWAPS = [
    ("2 x 150 Ah LiFePO4", "1 x 200 Ah LiFePO4 (Power Queen 200Ah Plus)", 19.2),
    ("Victron MultiPlus C", "Victron Phoenix 12/1200 inverter + Blue Smart IP22 12/30 charger", 7.9),
    ("SmartSolar MPPT", "Renogy DCC50S (DC-DC + MPPT) + Junctek shunt", 2.1),
    ("12 V cable", "12 V cable (thinner: 1200 W inverter) + 230 V + lugs", 13.0),
    ("2 solar panels", "2 x Sunstone 200 W (10 kg each) on DIY aluminium profiles on VW's rack points", 27.0),
    ("Grey tank", "Grey tank Varile NEO 80 L (stock)", 6.0),
    ("Whale Gulper", "Kemo tank level indicator (no shower pump: gravity drain)", 0.4),
    ("Truma Boiler B10", None, None),
    ("Pump (Shurflo", "Pump (Seaflo 42), filter, pipes, fittings", 9.0),
    ("Thetford Porta Potti 565E", "Thetford Porta Potti 335, dry", 4.2),
    ("Shower tray", "Shower tray, wet lining, curtain (no mixer: solar shower bag)", 12.0),
    ("Vitrifrigo C95L", "Indel B Cruise 85 OFF fridge, 85 L", 21.5),
    ("Thetford Topline 922", "Carbest 2-burner built-in gas hob", 2.5),
    ("Tefal Optimo", None, None),
    ("Quadron Anthony", "Cheap stainless sink, basic mixer, 10\" carbon filter", 5.0),
    ("3 x Dometic S4", "3 x Carbest Classic acrylic (2 x 900x450, 1 x 500x350)", 20.7),
    ("2 x MaxxFan", "1 x MaxxFan Deluxe + DIY adapter", 9.7),
    ("VanQuito", "DIY magnetic door fly screen", 0.5),
    ("Front engine guard", None, None),
    ("Rear diff", None, None),
    ("VB-SemiAir", None, None),
    ("Seikel", None, None),
    ("A/T tyres", "A/T tyres x 5 (General Grabber AT3) vs stock", 0.0),
    ("Breather", "Breather extensions, DIY kit", 0.8),
    # shell layers (cutlist.shell_groups names)
    ("Sound deadening", None, None),
    ("Insulation, walls", "Insulation - PIR 30 mm alu-faced on flat areas (~11 m2) + K-Flex 20 mm in the ribs (~11 m2)", 24.5),
    ("Glue for the foam", "Glue for the K-Flex half + foil tape on the PIR joints", 1.8),
    ("Cladding", "Cladding - 6 mm poplar on the ceiling only (~4.9 m2); stretch felt on the walls (~7.4 m2)", 13.2),
    # load
    ("Water heater full", "WC flush water", 15.0),
]
EXTRA = [("Furniture", "Thinner backs and shelves (6-9 mm instead of 12) - saving, est.", -8.0, 1700, "est.")]


def weight():
    base = P.run()
    rows, used = [], set()
    for g, n, kg, x, s in base["lines"]:
        for pre, new, nkg in SWAPS:
            if n.startswith(pre):
                used.add(pre)
                if new is not None:
                    rows.append((g, new, nkg, x, "low budget", kg))
                else:
                    rows.append((g, "(dropped) " + n, 0.0, x, "low budget", kg))
                break
        else:
            rows.append((g, n, kg, x, s, kg))
    missing = [p for p, _, _ in SWAPS if p not in used]
    assert not missing, missing
    rows += [(g, n, kg, x, s, 0.0) for g, n, kg, x, s in EXTRA]
    total, front, rear = P.KERB, P.KERB * P.KERB_FRONT_SHARE, P.KERB * (1 - P.KERB_FRONT_SHARE)
    groups = {}
    for g, n, kg, x, s, old in rows:
        f, r = P.axle(kg, x)
        total, front, rear = total + kg, front + f, rear + r
        groups.setdefault(g, [0.0, 0.0])
        groups[g][0] += kg
        groups[g][1] += old
    return base, dict(total=total, front=front, rear=rear, groups=groups, rows=rows)


def weight_report():
    base, low = weight()
    load_groups = ("People", "Water", "Gas", "Gear")
    build = sum(v[0] for g, v in low["groups"].items() if g not in load_groups)
    build0 = sum(v[1] for g, v in low["groups"].items() if g not in load_groups)
    empty = P.KERB + build
    test = empty + 75 * (P.SEATS - 1) + 10 * (P.SEATS + P.LENGTH_M)
    out = ["# Low budget — weight", "",
           "Generated by `python lowbudget.py` — do not edit by hand. Same model as "
           "[../payload.md](../payload.md); only the changed lines differ.", "",
           "| | v2-real | Low budget |", "|---|---|---|",
           "| Van as sold | %d | %d |" % (P.KERB, P.KERB),
           "| Build (conversion + upgrades) | %d | **%d** |" % (build0, build),
           "| Load (people, water, gear) | %d | %d |" % (base["total"] - P.KERB - build0,
                                                       low["total"] - P.KERB - build),
           "| **Total** | **%d** | **%d** |" % (base["total"], low["total"]),
           "| **Margin to 3500** | **%+d** | **%+d** |" % (3500 - base["total"], 3500 - low["total"]),
           "| Front axle (max 1800) | %d | %d |" % (base["front"], low["front"]),
           "| Rear axle (max 2100) | %d | %d |" % (base["rear"], low["rear"]),
           "| Registration test (empty + 2 x 75 + luggage allowance) | | %d |" % test, "",
           "## By group", "", "| Group | v2-real | Low budget | Change |", "|---|---|---|---|"]
    for g, (kg, old) in low["groups"].items():
        out.append("| %s | %d | %d | %+d |" % (g, old, kg, kg - old))
    out += ["", "## Changed lines", "", "| Group | Item | v2-real kg | Low budget kg |", "|---|---|---|---|"]
    for g, n, kg, x, s, old in low["rows"]:
        if s in ("low budget", "est.") and (kg != old or n.startswith("(dropped)") or s == "est."):
            out.append("| %s | %s | %.1f | %.1f |" % (g, n, old, kg))
    open(os.path.join(OUT, "weight.md"), "w").write("\n".join(out) + "\n")
    return base["total"], low["total"]


# Energy -----------------------------------------------------------------------------------
FRIDGE = 0.386                   # Indel B Cruise 85: 0.386 kWh/24 h at 25 C
INVERTER_IDLE_W = 9              # Phoenix 12/1200: ~8-10 W on (eco mode stalls with a laptop)
BATTERIES = [("1 x 200 Ah (chosen)", 200), ("2 x 200 Ah (+509 EUR, +19 kg)", 400)]
PANELS, AMPS = 2, 50             # 2 x 200 W; Renogy DCC50S, 50 A shared by sun and alternator


def day_use(day, hot, starlink=True):
    i = E.DAY_TYPES.index(day)
    rows = []
    for name, watts, hours, ac, _src in E.LOADS:
        if name.startswith(("Induction", "Oven", "Hot water")):
            kwh = 0.0                               # gas / dropped / no heater
        elif name.startswith("Fridge"):
            kwh = FRIDGE * (1.5 if hot else 1.0)
        elif name == "Starlink":
            kwh = 32 * hours[i] / 1000 if starlink else 0.0
        elif name.startswith("2 x MaxxFan"):
            kwh = watts * hours[i] / 1000 / 2       # one fan only
        elif name.startswith("Inverter idle"):
            kwh = INVERTER_IDLE_W * hours[i] / 1000
        else:
            kwh = watts * hours[i] / 1000
        if ac and not name.startswith("Inverter"):
            kwh /= E.INVERTER_EFF
        rows.append((name, kwh))
    return sum(k for _, k in rows), rows


def week(ah, place, starlink=True):
    usable = ah * 12.8 / 1000 * E.USABLE
    charge, short, low, log = usable, 0.0, 100.0, []
    for d, name in zip(E.WEEK, E.DAY_NAMES):
        use, _ = day_use(d, E.HOT[place], starlink)
        gain = PANELS * E.SUN[place] + E.DRIVE_HOURS[d] * AMPS * 13.4 / 1000
        charge = charge - use + gain
        if charge < 0:
            short, charge = short - charge, 0.0
        charge = min(charge, usable)
        low = min(low, 100 * charge / usable)
        log.append((name, d, use, gain, 100 * charge / usable))
    return low, short, log


def cell(low, short):
    return "%d %% · ok" % low if short < 0.05 else "0 %% · **%.1f kWh short**" % short


def energy_report():
    places = list(E.SUN)
    out = ["# Low budget — energy", "",
           "Generated by `python lowbudget.py` — do not edit by hand. Same week and sun as "
           "[../energy.md](../energy.md). Low budget: Indel B Cruise 85 fridge (0.386 kWh/day), "
           "Victron Phoenix 12/1200 idling ~9 W while on, no oven, cooking on gas, no water heater, "
           "one MaxxFan, Starlink Mini, 2 x 200 W panels, 50 A shared DC-DC + MPPT.", "",
           "## A parked working day", "", "| Load | v2-real | Low budget |", "|---|---|---|"]
    E_old = E.day_use("work_parked", False, lean=True, gas=True)
    new = day_use("work_parked", False)
    for (n, k0), (_, k1) in zip(E_old[1], new[1]):
        if k0 or k1:
            out.append("| %s | %.2f | %.2f |" % (n, k0, k1))
    out += ["| **Total, kWh** | **%.2f** | **%.2f** |" % (E_old[0], new[0]), "",
            "## A week without a campsite (lowest charge)", "",
            "| Set-up | " + " | ".join(places) + " |", "|---" * (len(places) + 1) + "|"]
    ref = [E.week(2, 50, p, True, (), True) for p in places]
    out.append("| v2-real: 300 Ah, 2 panels | " + " | ".join(cell(l, s) for l, s, _ in ref) + " |")
    for label, ah in BATTERIES:
        res = [week(ah, p) for p in places]
        out.append("| Low budget: %s | " % label + " | ".join(cell(l, s) for l, s, _ in res) + " |")
    res = [week(200, p, starlink=False) for p in places]
    out.append("| Low budget: 1 x 200 Ah, no Starlink (phone hotspot) | "
               + " | ".join(cell(l, s) for l, s, _ in res) + " |")
    out += ["", "## Day by day (1 x 200 Ah, Morocco in winter)", "",
            "| Day | Used kWh | Charged kWh | Charge at night |", "|---|---|---|---|"]
    for n, d, use, gain, pct in week(200, places[0])[2]:
        out.append("| %s | %.2f | %.2f | %d %% |" % (n, use, gain, pct))
    open(os.path.join(OUT, "energy.md"), "w").write("\n".join(out) + "\n")


if __name__ == "__main__":
    os.makedirs(OUT, exist_ok=True)
    print("weight v2-real %d, low budget %d" % weight_report())
    energy_report()
    print(open(os.path.join(OUT, "energy.md")).read())
